/**************************************************************************/
/* Copyright (c) 2020 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           9881

#define PATCH_ENTRY_CREATE_MUTE_OP               0x04003b89 /* $_create_mute_op */
#define PATCH_ENTRY_CBOPS_MUTE_ENABLE            0x04003bc3 /* $_cbops_mute_enable */
#define PATCH_ENTRY_CBOPS_MUTE_RESET             0x04003bc9 /* $_cbops_mute_reset */
#define PATCH_ENTRY_TTP_UPDATE_TTP_FROM_SOURCE_TIME 0x04003be5 /* $_ttp_update_ttp_from_source_time */
#define PATCH_ENTRY_GET_BT_ADDRESS               0x04003e63 /* $_get_bt_address */
#define PATCH_ENTRY_SET_LIC_DEBUG                0x04003f83 /* $_set_lic_debug */
#define PATCH_ENTRY_AUDIO_PIOS_SET_DIRECTION     0x04004bfd /* $_audio_pios_set_direction */
#define PATCH_ENTRY_AUDIO_PIOS_SET_OUTPUTS       0x04004c8b /* $_audio_pios_set_outputs */
#define PATCH_ENTRY_AUDIO_PIOS_GET_INPUTS        0x04004cc7 /* $_audio_pios_get_inputs */
#define PATCH_ENTRY_THREAD_OFFLOAD_RPC_IS_QUEUED 0x040053ab /* $_thread_offload_rpc_is_queued */
#define PATCH_ENTRY_THREAD_OFFLOAD_IS_ACTIVE     0x04005183 /* $_thread_offload_is_active */
#define PATCH_ENTRY_THREAD_OFFLOAD_IS_ENABLED    0x0400519d /* $_thread_offload_is_enabled */
#define PATCH_ENTRY_THREAD_OFFLOAD_QUEUE_RPC     0x040053eb /* $_thread_offload_queue_rpc */
#define PATCH_ENTRY_THREAD_OFFLOAD_UPDATE_P1_DM_LOCATION 0x040051b5 /* $_thread_offload_update_p1_dm_location */
#define PATCH_ENTRY_SETUP_CBOPS_DC_OFFSET_COMPENSATION 0x04006ac9 /* $_setup_cbops_dc_offset_compensation */

#endif /* SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H */
