#ifndef __EARBUD_TYM_PSID_H__
#define __EARBUD_TYM_PSID_H__

#define PSID_CUSTOMER0 200
#define PSID_DEBUG     (PSID_CUSTOMER0)
#define PSID_ANCTABLE  (PSID_CUSTOMER0 + 1)
#define PSID_BTNAME    (PSID_CUSTOMER0 + 2)
#define PSID_IRTH      (PSID_CUSTOMER0 + 3)
#define PSID_APPCONFIG (PSID_CUSTOMER0 + 4)
//#define PSID_CUSTOMUI  (PSID_CUSTOMER0 + 5)
#define PSID_BATT      (PSID_CUSTOMER0 + 5)
#define PSID_IRCONFIG  (PSID_CUSTOMER0 + 6)
// kings
#define PSID_PRESET_EQ (PSID_CUSTOMER0 + 7)

#endif /*__EARBUD_TYM_PSID_H__*/
