// Copyright 2018 Google LLC.
#ifndef GSOUND_TARGET_OSA_H
#define GSOUND_TARGET_OSA_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * This header file was generated by Google GSound Services,
 * it should not be altered in any way. Please treat this as
 * a read-only file.
 *
 * Each function listed below must
 * be implemented for each specific
 * platform / SDK
 *
 */
#include "gsound.h"

/**
 * This file contains the  target API for Operating System abstractions
 * including Int-locks, etc.
 */

/******************************************************************************
 * Interrupt Locks
 *****************************************************************************/

/**
 * Disable global interrupts.
 *
 * The function returns the state of the global interrupts (on or off)
 * prior to disabling. This will be used to restore interrupts
 *
 * return value can be opaque to caller
 */
uint32_t GSoundTargetOsIntLock(void);

/**
 * Revert interrupts give the last state.
 *
 * param[in]: int_status An opaque type returned from
 *                       GSoundTargetOsIntLock.
 */
void GSoundTargetOsIntRevert(uint32_t int_status);

/******************************************************************************
 * Timers
 *****************************************************************************/

/**
 * Return a free running counter in milliseconds.
 *
 * Counter should be free running from boot-up
 * and is not expected to roll over. Accuracy
 * of timer is not critical.
 */
uint32_t GSoundTargetOsGetTicksMs(void);

#ifdef __cplusplus
}
#endif

#endif  // GSOUND_TARGET_OSA_H
