/*!
\copyright  Copyright (c) 2019 Qualcomm Technologies International, Ltd.
            All Rights Reserved.
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\brief      Thermistor temperature voltage lookup table.
\note       Auto-generated by thermistor.py using constants:
                Namespace(BETA=3950.0, R0=10000.0, R_DIVIDER=10000.0, T0=25.0, TEMP_MAX=125, TEMP_MIN=-40, V_DIVIDER=1.8)
*/

#include "types.h"

/*! \brief The temperature corresponding to the first entry in #thermistor_voltage_lookup_table */
#define THERMISTOR_TEMP_MIN -40
/*! \brief The temperature corresponding to the final entry in #thermistor_voltage_lookup_table */
#define THERMISTOR_TEMP_MAX 125

/*! \brief A table of expected thermistor milli-voltage against temperature in the
           range THERMISTOR_TEMP_MIN to THERMISTOR_TEMP_MAX degrees Celsius */
static const uint16 thermistor_voltage_lookup_table[THERMISTOR_TEMP_MAX-THERMISTOR_TEMP_MIN+1] = {
    1756, // -40C
    1753, // -39C
    1749, // -38C
    1746, // -37C
    1742, // -36C
    1738, // -35C
    1733, // -34C
    1729, // -33C
    1724, // -32C
    1719, // -31C
    1714, // -30C
    1708, // -29C
    1702, // -28C
    1696, // -27C
    1690, // -26C
    1683, // -25C
    1676, // -24C
    1668, // -23C
    1660, // -22C
    1652, // -21C
    1644, // -20C
    1635, // -19C
    1625, // -18C
    1615, // -17C
    1605, // -16C
    1595, // -15C
    1584, // -14C
    1572, // -13C
    1561, // -12C
    1548, // -11C
    1536, // -10C
    1523, // -9C
    1509, // -8C
    1495, // -7C
    1481, // -6C
    1466, // -5C
    1451, // -4C
    1436, // -3C
    1420, // -2C
    1404, // -1C
    1387, // 0C
    1370, // 1C
    1352, // 2C
    1335, // 3C
    1317, // 4C
    1298, // 5C
    1280, // 6C
    1261, // 7C
    1242, // 8C
    1223, // 9C
    1203, // 10C
    1183, // 11C
    1163, // 12C
    1143, // 13C
    1123, // 14C
    1103, // 15C
    1082, // 16C
    1062, // 17C
    1042, // 18C
    1021, // 19C
    1001, // 20C
    980, // 21C
    960, // 22C
    940, // 23C
    920, // 24C
    900, // 25C
    880, // 26C
    860, // 27C
    840, // 28C
    821, // 29C
    802, // 30C
    783, // 31C
    764, // 32C
    745, // 33C
    727, // 34C
    709, // 35C
    691, // 36C
    674, // 37C
    657, // 38C
    640, // 39C
    623, // 40C
    607, // 41C
    591, // 42C
    575, // 43C
    560, // 44C
    545, // 45C
    530, // 46C
    516, // 47C
    502, // 48C
    488, // 49C
    475, // 50C
    462, // 51C
    449, // 52C
    437, // 53C
    424, // 54C
    413, // 55C
    401, // 56C
    390, // 57C
    379, // 58C
    368, // 59C
    358, // 60C
    348, // 61C
    338, // 62C
    328, // 63C
    319, // 64C
    310, // 65C
    301, // 66C
    293, // 67C
    285, // 68C
    277, // 69C
    269, // 70C
    261, // 71C
    254, // 72C
    247, // 73C
    240, // 74C
    233, // 75C
    227, // 76C
    220, // 77C
    214, // 78C
    208, // 79C
    202, // 80C
    197, // 81C
    191, // 82C
    186, // 83C
    181, // 84C
    176, // 85C
    171, // 86C
    166, // 87C
    162, // 88C
    157, // 89C
    153, // 90C
    149, // 91C
    145, // 92C
    141, // 93C
    137, // 94C
    134, // 95C
    130, // 96C
    127, // 97C
    123, // 98C
    120, // 99C
    117, // 100C
    114, // 101C
    111, // 102C
    108, // 103C
    105, // 104C
    102, // 105C
    100, // 106C
    97, // 107C
    95, // 108C
    92, // 109C
    90, // 110C
    88, // 111C
    85, // 112C
    83, // 113C
    81, // 114C
    79, // 115C
    77, // 116C
    75, // 117C
    73, // 118C
    72, // 119C
    70, // 120C
    68, // 121C
    67, // 122C
    65, // 123C
    63, // 124C
    62, // 125C
};

